"""add_templates_table

Revision ID: 2e3bb46b4c8c
Revises: 9b45ff4b9b53
Create Date: 2025-12-31 08:22:35.471341

"""
from typing import Sequence, Union
import json

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e3bb46b4c8c'
down_revision: Union[str, None] = '9b45ff4b9b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Default system templates - these match the hardcoded TEMPLATES from frontend/constants.tsx
SYSTEM_TEMPLATES = [
    {
        'id': '00000000-0000-0000-0000-000000000001',
        'name': 'How does this company actually make money?',
        'subtitle': 'SaaS Architecture',
        'description': 'Deep extraction of recurring revenue components, customer economics, and capital efficiency pillars.',
        'metrics': [
            {'id': 'arr', 'label': 'ARR / MRR', 'description': 'Annual or Monthly Recurring Revenue'},
            {'id': 'cac', 'label': 'Net CAC', 'description': 'Fully loaded Customer Acquisition Cost'},
            {'id': 'churn', 'label': 'Gross Churn %', 'description': 'Annualized customer logo or dollar churn'},
            {'id': 'margin', 'label': 'Gross Margin', 'description': 'Profitability after hosting and support costs'},
            {'id': 'payback', 'label': 'CAC Payback', 'description': 'Months required to recover acquisition costs'}
        ],
        'is_system': True,
    },
    {
        'id': '00000000-0000-0000-0000-000000000002',
        'name': 'Is this business investable?',
        'subtitle': 'Investment Analysis',
        'description': 'Structural financial metrics for asset valuation, debt leverage, and free cash flow distribution.',
        'metrics': [
            {'id': 'ebitda', 'label': 'Adj. EBITDA', 'description': 'Normalized earnings before interest, taxes, etc.'},
            {'id': 'netdebt', 'label': 'Net Leverage', 'description': 'Net Debt relative to earnings capacity'},
            {'id': 'fcf', 'label': 'Free Cash Flow', 'description': 'Cash available for distribution or reinvestment'},
            {'id': 'roic', 'label': 'ROIC %', 'description': 'Return on Invested Capital effectiveness'},
            {'id': 'pe', 'label': 'Forward P/E', 'description': 'Price relative to projected earnings'}
        ],
        'is_system': True,
    },
    {
        'id': '00000000-0000-0000-0000-000000000003',
        'name': 'Where am I exposed or fragile?',
        'subtitle': 'Portfolio Exposure',
        'description': 'Asset-level yield analysis, occupancy dynamics, and lease maturity profiling for property assets.',
        'metrics': [
            {'id': 'cap', 'label': 'Exit Cap Rate', 'description': 'Implied capitalization rate at terminal value'},
            {'id': 'noi', 'label': 'Cash NOI', 'description': 'Net Operating Income on a cash basis'},
            {'id': 'occ', 'label': 'Physical Occ. %', 'description': 'Percentage of rentable area physically occupied'},
            {'id': 'walt', 'label': 'WALT (Years)', 'description': 'Weighted Average Lease Term'},
            {'id': 'revpar', 'label': 'RevPAR', 'description': 'Revenue per available unit/room'}
        ],
        'is_system': True,
    },
    {
        'id': '00000000-0000-0000-0000-000000000004',
        'name': 'What am I missing?',
        'subtitle': 'Open Inquiry',
        'description': 'Zero-base inference engine. System automatically generates the optimal schema columns from uploaded data.',
        'metrics': [],
        'is_system': True,
    }
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('forked_from_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forked_from_id'], ['templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_templates_is_system', 'templates', ['is_system'], unique=False)
    op.create_index('ix_templates_user_id', 'templates', ['user_id'], unique=False)
    # ### end Alembic commands ###
    
    # Seed default system templates
    templates_table = sa.table('templates',
        sa.column('id', sa.UUID()),
        sa.column('name', sa.String()),
        sa.column('subtitle', sa.String()),
        sa.column('description', sa.Text()),
        sa.column('metrics', postgresql.JSONB()),
        sa.column('user_id', sa.UUID()),
        sa.column('is_system', sa.Boolean()),
        sa.column('forked_from_id', sa.UUID()),
    )
    
    for template in SYSTEM_TEMPLATES:
        op.execute(
            templates_table.insert().values(
                id=template['id'],
                name=template['name'],
                subtitle=template['subtitle'],
                description=template['description'],
                metrics=template['metrics'],  # Pass raw list for JSONB
                user_id=None,
                is_system=template['is_system'],
                forked_from_id=None,
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_templates_user_id', table_name='templates')
    op.drop_index('ix_templates_is_system', table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###

